# Generated by Django 5.1.4 on 2024-12-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_customer_location_mechanic_location_request_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='location',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='location',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
