# Generated by Django 5.1.4 on 2024-12-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Repairing', 'Repairing'), ('Repairing Done', 'Repairing Done')], default='Pending', max_length=50, null=True),
        ),
    ]
