# Generated by Django 5.1.4 on 2024-12-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_alter_request_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanic',
            old_name='status',
            new_name='is_premium',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='salary',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='premium_subscription_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
