# Generated by Django 5.1.4 on 2024-12-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_rename_status_mechanic_is_premium_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanic',
            old_name='is_premium',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='premium_subscription_date',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
