# Generated by Django 5.1.4 on 2024-12-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0017_remove_mechanic_salary_mechanic_subscription_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
